name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: [macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: go test
        run: go test -v .
